# Exercise W1 L2

In [4]:
# imports
import numpy as np
import pandas

# Matrices

## 1. Create a vector with 10 values (you choose) with the function “c”.

In [5]:
vec = np.arange(10)
vec

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 2. Build a 4×3 matrix with ones everywhere (using “matrix”).

In [6]:
matrix = np.ones((4,3))
matrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## 3. Build a 4×3 matrix, assigned to variable A, with the numbers 1 through 3 in each column.


In [12]:
A = np.outer(np.arange(3)+1, np.ones(4))
A[:,0]

array([1., 2., 3.])

## 4. Build a 4x3 matrix, assigned to B, with the numbers 1 to 4 in each row. 

In [15]:
B = np.outer(np.ones(3), np.arange(4)+1)
B[0,:]

array([1., 2., 3., 4.])

## 5. Extract the elements in the 1st and 2nd rows and 1st and 2nd columns of matrix A created above and assign to matrix S (you’ll have a 2×2 matrix).


In [16]:
S = A[0:2,0:2]
S

array([[1., 1.],
       [2., 2.]])

## 6. Build a 2x2 matrix filled with NAs.

In [17]:
NaNs = np.ones((2,2)) * np.nan
NaNs

array([[nan, nan],
       [nan, nan]])

----